# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKuRI1oD5YzXcqUESYuDIOTwdxutaeTY
"""

# Student Management System
# This program allows you to add, view, search, update, and delete students
# Data is stored in a list of dictionaries in memory

# Initialize an empty list to store student records
students = []

# Function to add a new student
def add_student():
    student_id = input("Enter Student ID: ")
    name = input("Enter Student Name: ")
    marks = float(input("Enter Student Marks: "))

    # Create a dictionary for the student
    student = {
        "id": student_id,
        "name": name,
        "marks": marks
    }
    # Add the dictionary to the students list
    students.append(student)
    print(f"Student {name} added successfully!\n")

# Function to view all students
def view_students():
    if not students:
        print("No students found.\n")
        return
    print("All Students:")
    for student in students:
        print(f"ID: {student['id']}, Name: {student['name']}, Marks: {student['marks']}")
    print()  # Blank line for spacing

# Function to search a student by ID
def search_student():
    search_id = input("Enter Student ID to search: ")
    found = False
    for student in students:
        if student['id'] == search_id:
            print(f"Student Found: ID: {student['id']}, Name: {student['name']}, Marks: {student['marks']}\n")
            found = True
            break
    if not found:
        print("Student not found.\n")

# Function to update student marks
def update_marks():
    update_id = input("Enter Student ID to update marks: ")
    found = False
    for student in students:
        if student['id'] == update_id:
            new_marks = float(input(f"Enter new marks for {student['name']}: "))
            student['marks'] = new_marks
            print(f"Marks updated for {student['name']}.\n")
            found = True
            break
    if not found:
        print("Student not found.\n")

# Function to delete a student
def delete_student():
    delete_id = input("Enter Student ID to delete: ")
    found = False
    for student in students:
        if student['id'] == delete_id:
            students.remove(student)
            print(f"Student {student['name']} deleted successfully.\n")
            found = True
            break
    if not found:
        print("Student not found.\n")

# Main menu loop
while True:
    print("=== Student Management System ===")
    print("1. Add Student")
    print("2. View All Students")
    print("3. Search Student")
    print("4. Update Student Marks")
    print("5. Delete Student")
    print("6. Exit")

    choice = input("Enter your choice (1-6): ")

    if choice == "1":
        add_student()
    elif choice == "2":
        view_students()
    elif choice == "3":
        search_student()
    elif choice == "4":
        update_marks()
    elif choice == "5":
        delete_student()
    elif choice == "6":
        print("Exiting program...")
        break
    else:
        print("Invalid choice! Please enter a number between 1-6.\n")

